### ISSUE TITLE
Zorua Crashing Game

### ISSUE THREAD

**Issue by ComicSams9** [InertSteak/Pokermon#389]
Whenever Zorua appear in the shop, when I move my cursor over it, the game crashes (crash log below). This happens regardless of the pokemon Zorua is copying in the shop, and has only happened since I updated the mod in the last couple of days. The only mods I have installed currently are Pokermon, Talisman, and Brainstorm.

Oops! The game crashed:
[SMODS Pokermon "pokemon/pokejokers_19.lua"]:118: attempt to index field 'nodes' (a nil value)

Additional Context:
Balatro Version: 1.0.1o-FULL
Modded Version: 1.0.0~BETA-0408c-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.7.1
Platform: Windows
Steamodded Mods:
    1: Brainstorm by OceanRamen [ID: Brainstorm, Version: 2.0.0-beta, Uses Lovely]
    2: Talisman by MathIsFun_, Mathguy24, jenwalter666, cg-223 [ID: Talisman, Version: 2.0.2, Uses Lovely]
        Break Infinity: omeganum
    3: Pokermon by InertSteak, Please See Credits Page [ID: Pokermon, Priority: -1, Version: 2.9.9-617a, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'generate_ui' at file 'pokemon/pokejokers_19.lua:118' (from mod with id Pokermon)
Local variables:
 self = table: 0x3a5a9d78  {ptype:Dark, _u:true, update:function: 0x3988d710, cost:8, order:178, _d:true, stage:Basic, original_mod:table: 0x3a0e24e0, discovered:true, pos:table: 0x3a091a68 (more...)}
 info_queue = table: 0x3b4b9c88  {1:table: 0x39c3ee20, 2:table: 0x3a15b040}
 card = table: 0x3c2617c8  {click_offset:table: 0x3ba2f4a0, children:table: 0x3c6b67e8, ambient_tilt:0.2, parent:table: 0x3b004768, under_overlay:false, T:table: 0x3c2619b8 (more...)}
 desc_nodes = table: 0x39c3ee88  {1:table: 0x3ba74058, 2:table: 0x3bbef470, 3:table: 0x3cbe8a60, 4:table: 0x3da7df90}
 specific_vars = table: 0x3a576a88  {sticker:white}
 full_UI_table = table: 0x3a576ae8  {badges:table: 0x3a2c5688, info:table: 0x39c3eeb0, main:table: 0x39c3ee88, card_type:Joker, name:table: 0x3a1f5e80, type:table: 0x3b4b9c60}
 _c = table: 0x3a5a9d78  {ptype:Dark, _u:true, update:function: 0x3988d710, cost:8, order:178, _d:true, stage:Basic, original_mod:table: 0x3a0e24e0, discovered:true, pos:table: 0x3a091a68 (more...)}
 _o = table: 0x3a0c1140  {alerted:true, loc_vars:function: 0x39b67ca8, _saved_d_u:true, original_key:roggenrola, ptype:Earth, mod:table: 0x3a0e24e0, registered:true, set_badges:function: 0x39e015e0 (more...)}
 temp_ability = table: 0x3a1b5ea8  {lightning_sticker:false, extra:table: 0x3cb10238, x_chips:1, hands_played_at_create:79, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
 (*temporary) = nil
 (*temporary) = table: 0x3a0c1140  {alerted:true, loc_vars:function: 0x39b67ca8, _saved_d_u:true, original_key:roggenrola, ptype:Earth, mod:table: 0x3a0e24e0, registered:true, set_badges:function: 0x39e015e0 (more...)}
 (*temporary) = table: 0x3b4b9c88  {1:table: 0x39c3ee20, 2:table: 0x3a15b040}
 (*temporary) = table: 0x3c2617c8  {click_offset:table: 0x3ba2f4a0, children:table: 0x3c6b67e8, ambient_tilt:0.2, parent:table: 0x3b004768, under_overlay:false, T:table: 0x3c2619b8 (more...)}
 (*temporary) = table: 0x39c3ee88  {1:table: 0x3ba74058, 2:table: 0x3bbef470, 3:table: 0x3cbe8a60, 4:table: 0x3da7df90}
 (*temporary) = table: 0x3a576a88  {sticker:white}
 (*temporary) = table: 0x3a576ae8  {badges:table: 0x3a2c5688, info:table: 0x39c3eeb0, main:table: 0x39c3ee88, card_type:Joker, name:table: 0x3a1f5e80, type:table: 0x3b4b9c60}
 (*temporary) = table: 0x3b4b9cd8  {vars:table: 0x3a1f5e08, set:Joker, type:descriptions, nodes:table: 0x39c3ee88, key:j_poke_roggenrola}
 (*temporary) = string: "attempt to index field 'nodes' (a nil value)"
(4) Lua method 'generate_UIBox_ability_table' at file 'functions/common_events.lua:2909'
Local variables:
 _c = table: 0x3a5a9d78  {ptype:Dark, _u:true, update:function: 0x3988d710, cost:8, order:178, _d:true, stage:Basic, original_mod:table: 0x3a0e24e0, discovered:true, pos:table: 0x3a091a68 (more...)}
 full_UI_table = table: 0x3a576ae8  {badges:table: 0x3a2c5688, info:table: 0x39c3eeb0, main:table: 0x39c3ee88, card_type:Joker, name:table: 0x3a1f5e80, type:table: 0x3b4b9c60}
 specific_vars = table: 0x3a576a88  {sticker:white}
 card_type = string: "Joker"
 badges = table: 0x3a2c5688  {force_rarity:true, card_type:Joker}
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = table: 0x3c2617c8  {click_offset:table: 0x3ba2f4a0, children:table: 0x3c6b67e8, ambient_tilt:0.2, parent:table: 0x3b004768, under_overlay:false, T:table: 0x3c2619b8 (more...)}
 first_pass = boolean: true
 desc_nodes = table: 0x39c3ee88  {1:table: 0x3ba74058, 2:table: 0x3bbef470, 3:table: 0x3cbe8a60, 4:table: 0x3da7df90}
 name_override = nil
 info_queue = table: 0x3b4b9c88  {1:table: 0x39c3ee20, 2:table: 0x3a15b040}
 loc_vars = table: 0x3b4b9cb0  {}
 cfg = table: 0x3a1b5ea8  {lightning_sticker:false, extra:table: 0x3cb10238, x_chips:1, hands_played_at_create:79, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
(5) Lua method 'hover' at file 'card.lua:4635'
Local variables:
 self = table: 0x3c2617c8  {click_offset:table: 0x3ba2f4a0, children:table: 0x3c6b67e8, ambient_tilt:0.2, parent:table: 0x3b004768, under_overlay:false, T:table: 0x3c2619b8 (more...)}
(6) Lua method 'update' at file 'engine/controller.lua:399'
Local variables:
 self = table: 0x39e5e1d0  {held_button_times:table: 0x39e5eaa0, focus_cursor_stack_level:1, snap_cursor_to:table: 0x3c249f88, interrupt:table: 0x39e5eaf0, GAMEPAD:table: 0x39e5f320 (more...)}
 dt = number: 0.00991114
(7) Lua upvalue 'gameUpdateRef' at file 'game.lua:2815'
Local variables:
 self = table: 0x399199c8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3b42d100, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x3a0d7fe8 (more...)}
 dt = number: 0.00991114
(8) Lua upvalue 'update_ref' at Steamodded file 'src/ui.lua:84' 
Local variables:
 self = table: 0x399199c8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3b42d100, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x3a0d7fe8 (more...)}
 dt = number: 0.00991114
(9) Lua upvalue 'upd' at file 'main.lua:1459'
Local variables:
 self = table: 0x399199c8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3b42d100, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x3a0d7fe8 (more...)}
 dt = number: 0.00991114
(10) Lua upvalue 'upd' at file 'main.lua:2137'
Local variables:
 self = table: 0x399199c8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3b42d100, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x3a0d7fe8 (more...)}
 dt = number: 0.00991114
(11) Lua method 'update' at file 'functions/pokeanimations.lua:95' (from mod with id Pokermon)
Local variables:
 self = table: 0x399199c8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3b42d100, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x3a0d7fe8 (more...)}
 dt = number: 0.00991114
(12) Lua upvalue 'oldupd' at file 'main.lua:995'
Local variables:
 dt = number: 0.00991114
(13) Lua field 'update' at file 'main.lua:2164'
Local variables:
 dt = number: 0.00991114
(14) Lua function '?' at file 'main.lua:934' (best guess)
(15) global C function 'xpcall'
(16) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 905 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by Hunter-Reboul** [comment]
I too have experienced this crash. Got the following error

`Oops! The game crashed:
[SMODS Pokermon "pokemon/pokejokers_19.lua"]:115: attempt to index a nil value

Additional Context:
Balatro Version: 1.0.1o-FULL
Modded Version: 1.0.0~BETA-0626b-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.8.0
Platform: Windows
Steamodded Mods:
    1: Pokermon by InertSteak, Please See Credits Page [ID: Pokermon, Version: 2.9.9-525a, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'generate_ui' at file 'pokemon/pokejokers_19.lua:115' (from mod with id Pokermon)
Local variables:
 self = table: 0x075f4bb8  {_discovered_unlocked_overwritten:true, in_pool:function: 0x075f4e80, _u:true, _d:false, _saved_d_u:true, original_key:zorua, original_mod:table: 0x07743a40 (more...)}
 info_queue = table: 0x075ce798  {1:table: 0x078d3340}
 card = table: 0x080b8628  {click_offset:table: 0x0785f058, children:table: 0x07f409c0, ambient_tilt:0.2, parent:table: 0x080f86e8, bypass_discovery_center:true, T:table: 0x077346b0 (more...)}
 desc_nodes = table: 0x07452838  {1:table: 0x07bdeff0, 2:table: 0x07f64700, 3:table: 0x078260b8}
 specific_vars = nil
 full_UI_table = table: 0x07452810  {badges:table: 0x074527b0, info:table: 0x07452860, type:table: 0x07452888, main:table: 0x07452838, card_type:Undiscovered, name:table: 0x07ec81b8 (more...)}
 _c = table: 0x075f4bb8  {_discovered_unlocked_overwritten:true, in_pool:function: 0x075f4e80, _u:true, _d:false, _saved_d_u:true, original_key:zorua, original_mod:table: 0x07743a40 (more...)}
 _o = table: 0x07448920  {loc_vars:function: 0x0761c908, _saved_d_u:true, original_key:bellsprout, ptype:Grass, mod:table: 0x07743a40, registered:true, _discovered_unlocked_overwritten:true (more...)}
 temp_ability = table: 0x07d30ec0  {lightning_sticker:false, extra:table: 0x07d30ee8, x_chips:1, hands_played_at_create:4, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
 (*temporary) = nil
 (*temporary) = table: 0x075d6f40  {set:Joker, type:name, nodes:table: 0x077f0a10, key:j_poke_bellsprout, AUT:table: 0x075d7058}
 (*temporary) = nil
 (*temporary) = table: 0x075d6fd0  {name_parsed:table: 0x07c0ba60}
 (*temporary) = nil
 (*temporary) = table: 0x07ec81b8  {1:table: 0x07ec81e0, 2:table: 0x07ec8298}
 (*temporary) = C function: builtin#6
 (*temporary) = table: 0x077f0a10  {1:table: 0x077f0a38, 2:table: 0x07d42a70}
 (*temporary) = number: 2
 (*temporary) = string: "attempt to index a nil value"
(4) Lua method 'generate_UIBox_ability_table' at file 'functions/common_events.lua:2810'
Local variables:
 _c = table: 0x075f4bb8  {_discovered_unlocked_overwritten:true, in_pool:function: 0x075f4e80, _u:true, _d:false, _saved_d_u:true, original_key:zorua, original_mod:table: 0x07743a40 (more...)}
 full_UI_table = table: 0x07452810  {badges:table: 0x074527b0, info:table: 0x07452860, type:table: 0x07452888, main:table: 0x07452838, card_type:Undiscovered, name:table: 0x07ec81b8 (more...)}
 specific_vars = nil
 card_type = string: "Undiscovered"
 badges = table: 0x074527b0  {1:dark_sticker, force_rarity:true}
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = table: 0x080b8628  {click_offset:table: 0x0785f058, children:table: 0x07f409c0, ambient_tilt:0.2, parent:table: 0x080f86e8, bypass_discovery_center:true, T:table: 0x077346b0 (more...)}
 first_pass = boolean: true
 desc_nodes = table: 0x07452838  {1:table: 0x07bdeff0, 2:table: 0x07f64700, 3:table: 0x078260b8}
 name_override = nil
 info_queue = table: 0x075ce798  {1:table: 0x078d3340}
 loc_vars = table: 0x077f0af0  {}
 cfg = table: 0x07d30ec0  {lightning_sticker:false, extra:table: 0x07d30ee8, x_chips:1, hands_played_at_create:4, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
(5) Lua method 'hover' at file 'card.lua:4636'
Local variables:
 self = table: 0x080b8628  {click_offset:table: 0x0785f058, children:table: 0x07f409c0, ambient_tilt:0.2, parent:table: 0x080f86e8, bypass_discovery_center:true, T:table: 0x077346b0 (more...)}
(6) Lua method 'update' at file 'engine/controller.lua:399'
Local variables:
 self = table: 0x0772daf8  {held_button_times:table: 0x0772e3c8, focus_cursor_stack_level:1, snap_cursor_to:table: 0x078199a8, interrupt:table: 0x0772e418, GAMEPAD:table: 0x0772ec48 (more...)}
 dt = number: 0.0166658
(7) Lua upvalue 'gameUpdateRef' at file 'game.lua:2706'
Local variables:
 self = table: 0x072b28d8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x080c01e0, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x0804a658 (more...)}
 dt = number: 0.0166658
(8) Lua upvalue 'upd' at Steamodded file 'src/ui.lua:84' 
Local variables:
 self = table: 0x072b28d8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x080c01e0, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x0804a658 (more...)}
 dt = number: 0.0166658
(9) Lua method 'update' at file 'functions/pokeanimations.lua:94' (from mod with id Pokermon)
Local variables:
 self = table: 0x072b28d8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x080c01e0, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x0804a658 (more...)}
 dt = number: 0.0166658
(10) Lua field 'update' at file 'main.lua:995'
Local variables:
 dt = number: 0.0166658
(11) Lua function '?' at file 'main.lua:934' (best guess)
(12) global C function 'xpcall'
(13) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 905 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
`

Also crashed when I tried opening a pack with Zorua in the shop. Was able to move to the next round though.

**Comment by InertSteak** [comment]
Yeah this is a known issue that's been fixed in the latest code, and a new release version with the fix will be out soon.

**Comment by ComicSams9** [comment]
I have updated to the newest version of the mod, but I am still getting this crash with Zorua in the shop.

Oops! The game crashed:
[SMODS Pokermon "pokemon/pokejokers_19.lua"]:118: attempt to index field 'nodes' (a nil value)

Additional Context:
Balatro Version: 1.0.1o-FULL
Modded Version: 1.0.0~BETA-0408c-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.7.1
Platform: Windows
Steamodded Mods:
    1: Brainstorm by OceanRamen [ID: Brainstorm, Version: 2.0.0-beta, Uses Lovely]
    2: Talisman by MathIsFun_, Mathguy24, jenwalter666, cg-223 [ID: Talisman, Version: 2.0.2, Uses Lovely]
        Break Infinity: omeganum
    3: Pokermon by InertSteak, Please See Credits Page [ID: Pokermon, Priority: -1, Version: 3.0.0-704a, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'generate_ui' at file 'pokemon/pokejokers_19.lua:118' (from mod with id Pokermon)
Local variables:
 self = table: 0x275ac6f0  {ptype:Dark, _u:true, update:function: 0x2734c8e8, cost:8, order:180, _d:true, stage:Basic, original_mod:table: 0x270d7900, discovered:true, pos:table: 0x275ac718 (more...)}
 info_queue = table: 0x289a6070  {1:table: 0x289a62a0, 2:table: 0x289a6300, 3:table: 0x26f522c0}
 card = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
 desc_nodes = table: 0x289a5ff8  {1:table: 0x289a6d50, 2:table: 0x28dbaa00, 3:table: 0x274391d0, 4:table: 0x27439f68}
 specific_vars = table: 0x289a5f08  {sticker:white}
 full_UI_table = table: 0x289a5f68  {badges:table: 0x289a5ea8, info:table: 0x289a6020, main:table: 0x289a5ff8, card_type:Joker, name:table: 0x289a6548, type:table: 0x289a6048}
 _c = table: 0x275ac6f0  {ptype:Dark, _u:true, update:function: 0x2734c8e8, cost:8, order:180, _d:true, stage:Basic, original_mod:table: 0x270d7900, discovered:true, pos:table: 0x275ac718 (more...)}
 _o = table: 0x26b97c18  {alerted:true, loc_vars:function: 0x26e082f8, _saved_d_u:true, original_key:cleffa, _discovered_unlocked_overwritten:true, ptype:Fairy, mod:table: 0x270d7900 (more...)}
 temp_ability = table: 0x26ff3440  {lightning_sticker:false, extra:table: 0x273bb460, x_chips:1, hands_played_at_create:40, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
 (*temporary) = nil
 (*temporary) = table: 0x26b97c18  {alerted:true, loc_vars:function: 0x26e082f8, _saved_d_u:true, original_key:cleffa, _discovered_unlocked_overwritten:true, ptype:Fairy, mod:table: 0x270d7900 (more...)}
 (*temporary) = table: 0x289a6070  {1:table: 0x289a62a0, 2:table: 0x289a6300, 3:table: 0x26f522c0}
 (*temporary) = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
 (*temporary) = table: 0x289a5ff8  {1:table: 0x289a6d50, 2:table: 0x28dbaa00, 3:table: 0x274391d0, 4:table: 0x27439f68}
 (*temporary) = table: 0x289a5f08  {sticker:white}
 (*temporary) = table: 0x289a5f68  {badges:table: 0x289a5ea8, info:table: 0x289a6020, main:table: 0x289a5ff8, card_type:Joker, name:table: 0x289a6548, type:table: 0x289a6048}
 (*temporary) = table: 0x289a6188  {vars:table: 0x289a6418, set:Joker, type:descriptions, nodes:table: 0x289a5ff8, key:j_poke_cleffa}
 (*temporary) = string: "attempt to index field 'nodes' (a nil value)"
(4) Lua method 'generate_UIBox_ability_table' at file 'functions/common_events.lua:2909'
Local variables:
 _c = table: 0x275ac6f0  {ptype:Dark, _u:true, update:function: 0x2734c8e8, cost:8, order:180, _d:true, stage:Basic, original_mod:table: 0x270d7900, discovered:true, pos:table: 0x275ac718 (more...)}
 full_UI_table = table: 0x289a5f68  {badges:table: 0x289a5ea8, info:table: 0x289a6020, main:table: 0x289a5ff8, card_type:Joker, name:table: 0x289a6548, type:table: 0x289a6048}
 specific_vars = table: 0x289a5f08  {sticker:white}
 card_type = string: "Joker"
 badges = table: 0x289a5ea8  {force_rarity:true, card_type:Joker}
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
 first_pass = boolean: true
 desc_nodes = table: 0x289a5ff8  {1:table: 0x289a6d50, 2:table: 0x28dbaa00, 3:table: 0x274391d0, 4:table: 0x27439f68}
 name_override = nil
 info_queue = table: 0x289a6070  {1:table: 0x289a62a0, 2:table: 0x289a6300, 3:table: 0x26f522c0}
 loc_vars = table: 0x289a6160  {}
 cfg = table: 0x26ff3440  {lightning_sticker:false, extra:table: 0x273bb460, x_chips:1, hands_played_at_create:40, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
(5) Lua method 'hover' at file 'card.lua:4635'
Local variables:
 self = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
(6) Lua method 'update' at file 'engine/controller.lua:399'
Local variables:
 self = table: 0x26e7ad88  {held_button_times:table: 0x26e7b658, focus_cursor_stack_level:1, snap_cursor_to:table: 0x2873ec28, interrupt:table: 0x26e7b6a8, GAMEPAD:table: 0x26e7bed8 (more...)}
 dt = number: 0.00688767
(7) Lua upvalue 'gameUpdateRef' at file 'game.lua:2815'
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(8) Lua upvalue 'update_ref' at Steamodded file 'src/ui.lua:84' 
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(9) Lua upvalue 'upd' at file 'main.lua:1459'
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(10) Lua upvalue 'upd' at file 'main.lua:2137'
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(11) Lua method 'update' at file 'functions/pokeanimations.lua:95' (from mod with id Pokermon)
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(12) Lua upvalue 'oldupd' at file 'main.lua:995'
Local variables:
 dt = number: 0.00688767
(13) Lua field 'update' at file 'main.lua:2164'
Local variables:
 dt = number: 0.00688767
(14) Lua function '?' at file 'main.lua:934' (best guess)
(15) global C function 'xpcall'
(16) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 905 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by ComicSams9** [comment]
I have updated to the newest version of the mod and I'm still getting this error. Zorua still crashes the game in the shop.

Oops! The game crashed:
[SMODS Pokermon "pokemon/pokejokers_19.lua"]:118: attempt to index field 'nodes' (a nil value)

Additional Context:
Balatro Version: 1.0.1o-FULL
Modded Version: 1.0.0~BETA-0408c-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.7.1
Platform: Windows
Steamodded Mods:
    1: Brainstorm by OceanRamen [ID: Brainstorm, Version: 2.0.0-beta, Uses Lovely]
    2: Talisman by MathIsFun_, Mathguy24, jenwalter666, cg-223 [ID: Talisman, Version: 2.0.2, Uses Lovely]
        Break Infinity: omeganum
    3: Pokermon by InertSteak, Please See Credits Page [ID: Pokermon, Priority: -1, Version: 3.0.0-704a, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'generate_ui' at file 'pokemon/pokejokers_19.lua:118' (from mod with id Pokermon)
Local variables:
 self = table: 0x275ac6f0  {ptype:Dark, _u:true, update:function: 0x2734c8e8, cost:8, order:180, _d:true, stage:Basic, original_mod:table: 0x270d7900, discovered:true, pos:table: 0x275ac718 (more...)}
 info_queue = table: 0x289a6070  {1:table: 0x289a62a0, 2:table: 0x289a6300, 3:table: 0x26f522c0}
 card = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
 desc_nodes = table: 0x289a5ff8  {1:table: 0x289a6d50, 2:table: 0x28dbaa00, 3:table: 0x274391d0, 4:table: 0x27439f68}
 specific_vars = table: 0x289a5f08  {sticker:white}
 full_UI_table = table: 0x289a5f68  {badges:table: 0x289a5ea8, info:table: 0x289a6020, main:table: 0x289a5ff8, card_type:Joker, name:table: 0x289a6548, type:table: 0x289a6048}
 _c = table: 0x275ac6f0  {ptype:Dark, _u:true, update:function: 0x2734c8e8, cost:8, order:180, _d:true, stage:Basic, original_mod:table: 0x270d7900, discovered:true, pos:table: 0x275ac718 (more...)}
 _o = table: 0x26b97c18  {alerted:true, loc_vars:function: 0x26e082f8, _saved_d_u:true, original_key:cleffa, _discovered_unlocked_overwritten:true, ptype:Fairy, mod:table: 0x270d7900 (more...)}
 temp_ability = table: 0x26ff3440  {lightning_sticker:false, extra:table: 0x273bb460, x_chips:1, hands_played_at_create:40, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
 (*temporary) = nil
 (*temporary) = table: 0x26b97c18  {alerted:true, loc_vars:function: 0x26e082f8, _saved_d_u:true, original_key:cleffa, _discovered_unlocked_overwritten:true, ptype:Fairy, mod:table: 0x270d7900 (more...)}
 (*temporary) = table: 0x289a6070  {1:table: 0x289a62a0, 2:table: 0x289a6300, 3:table: 0x26f522c0}
 (*temporary) = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
 (*temporary) = table: 0x289a5ff8  {1:table: 0x289a6d50, 2:table: 0x28dbaa00, 3:table: 0x274391d0, 4:table: 0x27439f68}
 (*temporary) = table: 0x289a5f08  {sticker:white}
 (*temporary) = table: 0x289a5f68  {badges:table: 0x289a5ea8, info:table: 0x289a6020, main:table: 0x289a5ff8, card_type:Joker, name:table: 0x289a6548, type:table: 0x289a6048}
 (*temporary) = table: 0x289a6188  {vars:table: 0x289a6418, set:Joker, type:descriptions, nodes:table: 0x289a5ff8, key:j_poke_cleffa}
 (*temporary) = string: "attempt to index field 'nodes' (a nil value)"
(4) Lua method 'generate_UIBox_ability_table' at file 'functions/common_events.lua:2909'
Local variables:
 _c = table: 0x275ac6f0  {ptype:Dark, _u:true, update:function: 0x2734c8e8, cost:8, order:180, _d:true, stage:Basic, original_mod:table: 0x270d7900, discovered:true, pos:table: 0x275ac718 (more...)}
 full_UI_table = table: 0x289a5f68  {badges:table: 0x289a5ea8, info:table: 0x289a6020, main:table: 0x289a5ff8, card_type:Joker, name:table: 0x289a6548, type:table: 0x289a6048}
 specific_vars = table: 0x289a5f08  {sticker:white}
 card_type = string: "Joker"
 badges = table: 0x289a5ea8  {force_rarity:true, card_type:Joker}
 hide_desc = nil
 main_start = nil
 main_end = nil
 card = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
 first_pass = boolean: true
 desc_nodes = table: 0x289a5ff8  {1:table: 0x289a6d50, 2:table: 0x28dbaa00, 3:table: 0x274391d0, 4:table: 0x27439f68}
 name_override = nil
 info_queue = table: 0x289a6070  {1:table: 0x289a62a0, 2:table: 0x289a6300, 3:table: 0x26f522c0}
 loc_vars = table: 0x289a6160  {}
 cfg = table: 0x26ff3440  {lightning_sticker:false, extra:table: 0x273bb460, x_chips:1, hands_played_at_create:40, mult:0, grass_sticker:false, h_x_chips:1, perma_mult:0 (more...)}
(5) Lua method 'hover' at file 'card.lua:4635'
Local variables:
 self = table: 0x26d2bfc8  {click_offset:table: 0x27014a50, children:table: 0x28602cc8, ambient_tilt:0.2, parent:table: 0x274d3b30, under_overlay:false, T:table: 0x28920548 (more...)}
(6) Lua method 'update' at file 'engine/controller.lua:399'
Local variables:
 self = table: 0x26e7ad88  {held_button_times:table: 0x26e7b658, focus_cursor_stack_level:1, snap_cursor_to:table: 0x2873ec28, interrupt:table: 0x26e7b6a8, GAMEPAD:table: 0x26e7bed8 (more...)}
 dt = number: 0.00688767
(7) Lua upvalue 'gameUpdateRef' at file 'game.lua:2815'
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(8) Lua upvalue 'update_ref' at Steamodded file 'src/ui.lua:84' 
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(9) Lua upvalue 'upd' at file 'main.lua:1459'
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(10) Lua upvalue 'upd' at file 'main.lua:2137'
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(11) Lua method 'update' at file 'functions/pokeanimations.lua:95' (from mod with id Pokermon)
Local variables:
 self = table: 0x269298e8  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2886da88, F_ENGLISH_ONLY:false, viewed_stake:1, HUD:table: 0x2871f728 (more...)}
 dt = number: 0.00688767
(12) Lua upvalue 'oldupd' at file 'main.lua:995'
Local variables:
 dt = number: 0.00688767
(13) Lua field 'update' at file 'main.lua:2164'
Local variables:
 dt = number: 0.00688767
(14) Lua function '?' at file 'main.lua:934' (best guess)
(15) global C function 'xpcall'
(16) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 905 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
